import { useState } from 'react'
import type { useFirmwareBuild } from '../hooks/useFirmwareBuild'
import { Icon } from './Icon'
function saveFirmware(buffer:ArrayBuffer,name:string) {
  const url=URL.createObjectURL(new Blob([buffer],{type:'application/octet-stream'})),link=document.createElement('a')
  link.href=url;link.download=(name.replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'')||'octamod')+'-OCTAMOD79.bin'
  document.body.append(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)
}
export function FirmwareBuildPanel({build,available,downloadsEnabled,firmwareReady,moduleCount,riskAccepted,configurationName,onExport,exported}:{build:ReturnType<typeof useFirmwareBuild>;available:boolean;downloadsEnabled:boolean;firmwareReady:boolean;moduleCount:number;riskAccepted:boolean;configurationName:string;onExport:()=>void;exported:boolean}){
  const [downloadedKey,setDownloadedKey]=useState('')
  const progress=build.phase==='packing'?'Packing your firmware…':build.phase==='verifying'?'Verifying the finished file…':'Composing your selected modules…'
  const ready=build.state==='valid',finished=build.state==='built'&&!!build.result
  const message=!firmwareReady?'Choose your original OS 1.40C file first.':!moduleCount?'Add at least one module from the library.':build.state==='validating'?'Checking this configuration’s memory placement…':build.state==='building'?progress:build.state==='error'?build.error:finished&&!downloadsEnabled?'This configuration builds and passes its local checks. Downloads are paused, so no file is offered.':finished?'Firmware is ready. The finished file passed its local packaging integrity check.':'This selection fits. Build it locally when you’re ready.'
  return <>
    {!downloadsEnabled&&<aside className="risk-note" role="note"><strong>Firmware downloads are paused</strong><p>In a test on a real Octatrack, firmware using the same effect-loading method could not load effects and played no audio. Octamod will offer files again once a fix has been confirmed on hardware. You can still build to check that a configuration fits.</p></aside>}
    <section className="build-section" aria-labelledby="build-title" aria-busy={build.state==='building'||build.state==='validating'}>
      <div><h2 id="build-title">{finished?'Firmware ready':'Build firmware'}</h2><p id="engine-status" role={build.state==='error'?'alert':'status'}>{message}</p><span className="subtle">No firmware upload. Local validation does not qualify this configuration on hardware.</span></div>
      <div className="build-actions">
        {build.state==='building'?<button className="button button-quiet" onClick={build.cancel}>Cancel build</button>:finished&&!downloadsEnabled?null:finished?<button className="button button-primary" disabled={!riskAccepted} aria-describedby="engine-status" onClick={()=>{saveFirmware(build.result!.buffer,configurationName);setDownloadedKey(build.key)}}><Icon name="download" size={16}/>Download .bin</button>:<button className="button button-primary" disabled={!available||!ready||!riskAccepted} onClick={()=>void build.build()} aria-describedby="engine-status"><Icon name="sliders" size={16}/>Build firmware</button>}
        {build.state==='error'&&<button className="button button-quiet" onClick={build.retry}>Check again</button>}
        <button className="button button-quiet" onClick={onExport}><Icon name="download" size={16}/>Export configuration</button><p className="export-note" aria-live="polite">{exported?'Configuration exported as JSON.':'JSON backup · no firmware included'}</p>
      </div>
    </section>
    {build.report&&<div className="build-facts"><span>FX1 <strong>{build.report.fx1Rows} effects</strong></span><span>FX2 <strong>{build.report.fx2Rows} effects</strong></span><span>OS image <strong>{(build.report.osBytes/1024).toFixed(1)} KB</strong></span>{finished&&<span>Download <strong>{(build.result!.buffer.byteLength/1024).toFixed(1)} KB</strong></span>}</div>}
    {finished&&downloadsEnabled&&<section className="configuration-section install-guide" aria-labelledby="install-title"><div className="section-title"><h2 id="install-title">Install on your Octatrack</h2><span className="pill">{build.report?.version}</span></div><p className="service-note">Keep your original OS 1.40C file and back up projects, banks and samples. This module configuration reserves about 10 MB of sample memory for its runtime.</p><ol><li>Download the .bin and copy it to the root of the Octatrack’s CompactFlash card.</li><li>Unmount the card safely, then choose OS UPGRADE from the Octatrack’s system settings and confirm the prompts. Follow the manual for your model. Use a stable power supply and never interrupt an update.</li><li>After updating, confirm the displayed OS version and test the selected effects with a backup project before using the firmware in a live set.</li></ol><p><a href="https://www.elektron.se/wp-content/uploads/2024/09/Octatrack-MKII-User-Manual_ENG_OS1.40A_210414.pdf" target="_blank" rel="noreferrer">Official MKII manual, §8.5.2 ↗</a> · <a href="https://www.elektron.se/wp-content/uploads/2024/09/Octatrack-User-Manual_ENG-OS1.40A_220204.pdf" target="_blank" rel="noreferrer">MKI manual, §8.5.2 ↗</a></p><p className="service-note">Flash at your own risk. Emulator evidence and local integrity checks cannot guarantee hardware safety.</p><details><summary>File identity & source revision</summary><dl className="build-identity"><dt>SHA-256</dt><dd>{build.result!.sha256}</dd><dt>Module versions</dt><dd>{Object.entries(build.report?.moduleVersions??{}).map(([id,version])=>id+' '+version).join(', ')}</dd><dt>Source commit</dt><dd>{build.report?.sourceCommit??'Local development build'}</dd><dt>Source fingerprint</dt><dd>{build.report?.sourceTreeSha256}</dd><dt>Native profile</dt><dd>{build.report?.revision}</dd></dl></details>{downloadedKey===build.key&&<p className="success-note" role="status">Download requested. Check your browser’s downloads folder before copying the file.</p>}</section>}
  </>
}
